CREATE TABLE IF NOT EXISTS cart (
    id SERIAL PRIMARY KEY,
    productid INT NOT NULL REFERENCES product(id) ON DELETE CASCADE,
    quantity INT NOT NULL,
    createdat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    userid INT NOT NULL REFERENCES users(id)
);